import { Roboto } from 'next/font/google'
import './globals.css'
import Footer from './Footer'
import Navbar from './navbar'
const roboto = Roboto({ subsets: ['latin'],weight:['100', '300', '400', '500', '700', '900'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
         <Navbar />
         <div className='pt-16'>
        {children}
         </div>
        <Footer/>
        </body>
    </html>
  )
}
