export const ReviewsInfo = [
  {
    order: "1",
    image:
      "https://res.cloudinary.com/dm9udoven/image/upload/v1700780756/best7vpn/cyberghost_vpn_kbrr9a.svg",
    name: "",
    startAt: "12.99",
    starsNum: 9,
    description:
      "CyberGhost VPN: Fast, secure, and easy-to-use service for all major operating systems and devices. Unlimited bandwidth, no logs, streaming-optimized servers, and a 45-day money-back guarantee. Encrypts online traffic, hides real IP address, ensuring privacy and security on any device. Connect up to 7 devices simultaneously with just 1 subscription. App available for Windows, macOS, Android, iOS, and Linux; can be configured with routers, Smart TVs, Amazon Fire TV Stick, or game consoles. Large server fleet across America, Europe, Africa, and Asia for accessing favorite content. Fast speeds for streaming, downloading, and online gaming.",
    link: "my affiliation link",
  },
  {
    order: "2",
    image: "",
    name: "",
    startAt: "",
    starsNum: 9,
    description: "",
    link: "",
  },
  {
    order: "3",
    image: "",
    name: "",
    startAt: "",
    starsNum: 9,
    description: "",
    link: "",
  },
  {
    order: "4",
    image: "",
    name: "",
    startAt: "",
    starsNum: 9,
    description: "",
    link: "",
  },
  {
    order: "5",
    image: "",
    name: "",
    startAt: "",
    starsNum: 9,
    description: "",
    link: "",
  },
  {
    order: "6",
    image: "",
    name: "",
    startAt: "",
    starsNum: 9,
    description: "",
    link: "",
  },
  {
    order: "7",
    image: "",
    name: "",
    startAt: "",
    starsNum: 9,
    description: "",
    link: "",
  },
];
